#!/bin/bash
# this script needs to be executed from this directory only!!

set -e

source .env

# rclone pull to cloudstream
echo "pulling from dropbox..."
rclone copy "$REMOTENAME:$REMOTE_FOLDER" "$HOT1$HOT_CLOUDSTREAM_NAME"

# chronologize these
echo "chronologizing..."
./chronologizer/chronologize "$HOT1$HOT_CLOUDSTREAM_NAME"

# copy these to other hot drives photos dir using backup 
echo "populating to other hot drives"
./backinUp/backup "$HOT1$HOT_CLOUDSTREAM_NAME" "$HOT2$HOT_PHOTOS_NAME"

# copy these to disc photos using backup
echo "copying to discovery drive"
./backinUp/backup "$HOT1$HOT_CLOUDSTREAM_NAME" "${DISC}${DISC_PHOTOS_NAME}sampleDir/"

# move these to curr hot drive downstream using backup
./backinUp/backup "$HOT1$HOT_CLOUDSTREAM_NAME" "$HOT1$HOT_DOWNSTREAM_NAME"
rm -r "${HOT1}${HOT_CLOUDSTREAM_NAME}"*


# update home gallery import initial
sudo docker compose run -T gallery run import --update


# delete these photos from disc drive


# check for space and buffer in hot and disc, set envs


# delete from dropbox using rclone
echo "deleting from dropbox"
rclone delete "$REMOTENAME:$REMOTE_FOLDER"
