#!/bin/bash
# this script needs to be executed from this directory only!!

set -e

source .env

# rclone pull to cloudstream
rclone copy "$REMOTENAME:$REMOTE_FOLDER" "$HOT1$HOT_CLOUDSTREAM_NAME"

# chronologize these
./chronologizer/chronologize "$HOT1$HOT_CLOUDSTREAM_NAME"

# copy these to other hot drives downstream dir using backup 
./backinUP/backup "$HOT1$HOT_CLOUDSTREAM_NAME" "$HOT2$HOT_DOWNSTREAM_NAME"

# copy these to disc photos using backup
./backinUP/backup "$HOT1$HOT_CLOUDSTREAM_NAME" "$DISC$DISC_PHOTOS_NAME/sampleDir/"

# move these to curr hot drive downstream using backup
./backinUP/backup "$HOT1$HOT_CLOUDSTREAM_NAME" "$HOT1$HOT_DOWNSTREAM_NAME"
rm -r "$HOT1$HOT_CLOUDSTREAM_NAME/*"


# update home gallery import initial
docker-compose run -T gallery run import --update


# delete these photos from disc drive


# check for space and buffer in hot and disc, set envs


# delete from dropbox using rclone
rclone delete "$REMOTENAME:$REMOTE_FOLDER"
