#!/bin/bash
set -e


SRC="$1" # new uploads folder
DEST="$2"


cd "$SRC"

for i in *
do
    if [ -d "$i" ]
    then
        cd "$i"
        mkdir -p "$DEST$i"
        cp * "$DEST$i"
        cd ..
        # move files from new uploads to homegallery folder
    fi
done